"""init

Revision ID: 7b979d7dfc4a
Revises: 0f170951304a
Create Date: 2025-03-23 20:44:31.004803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b979d7dfc4a'
down_revision = '0f170951304a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
