"""init

Revision ID: 7b857b0a3b8f
Revises: f9c9c39a3099
Create Date: 2025-03-23 20:55:17.552169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b857b0a3b8f'
down_revision = 'f9c9c39a3099'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
