"""init

Revision ID: 55518990e05d
Revises: 7b979d7dfc4a
Create Date: 2025-03-23 20:50:16.273349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55518990e05d'
down_revision = '7b979d7dfc4a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
