"""init

Revision ID: f9c9c39a3099
Revises: 55518990e05d
Create Date: 2025-03-23 20:54:23.399612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c9c39a3099'
down_revision = '55518990e05d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
